"""Emit a calibrated Krauss vTypes XML; optional grid-search if sat-flow lands.

What this script DOES today: writes ``vTypes_calibrated.add.xml`` with
Krauss tau / sigma / decel pinned to literature midpoints (HCM 6th
Edition + SUMO docs), with every value's source recorded inline as an
XML comment. The point is to take vehicle dynamics off the implicit
"SUMO defaults" footing and onto an explicit, auditable line. The V1
regression still passes on these values because they're within the
band SUMO's own defaults already sit in -- this is not a behavioral
change today, it's a provenance change.

What this script will DO once saturation-flow surveys land: with
``--saturation-flow-target <veh/h/lane>`` and ``--bottleneck-edge <id>``
it runs a small grid search over (tau, sigma, decel), driving SUMO via
TraCI on a one-edge bottleneck, picking the combination that minimises
squared error between simulated steady-state discharge and the target
flow. Results overwrite the literature defaults and update the
provenance attribute. Requires SUMO on PATH.

The plan's original framing -- "fit against real_world_counts.xml
queue-discharge slopes" -- doesn't quite hold: real_world_counts.xml
carries 1-hour entered totals, not discharge slopes (no per-cycle
breakdown survives the routeSampler input format). The grid-search
framework is set up for the right data once City of Bellevue / WSDOT
returns saturation-flow surveys -- see ``report.md`` R3.

Usage (from ``SUMO/v2``):

    # Today, literature defaults:
    python -m ai.sumo_calibration.calibrate_carfollow

    # Once sat-flow data arrives (per-lane veh/h on a free-flow bottleneck):
    python -m ai.sumo_calibration.calibrate_carfollow \\
        --saturation-flow-target 1900 \\
        --bottleneck-edge 513503507 \\
        --sumo-cfg sim_calibrated.sumocfg
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Optional


# Literature-anchored defaults. Each value carries its source so any
# audit can trace why this number and not another. SUMO's own defaults
# sit a hair on the conservative side of these (tau=1.0, sigma=0.5)
# which keeps V1's existing regression intact when we swap in this file.
@dataclass
class KraussParams:
    accel: float = 2.6
    decel: float = 4.5
    tau: float = 1.0
    sigma: float = 0.5
    minGap: float = 2.5
    maxSpeed: float = 22.22  # 50 mph corridor, m/s
    length: float = 5.0
    # ``apparentDecel`` is what other vehicles assume this one can do --
    # SUMO uses it for safety distance calc. Setting it equal to decel
    # eliminates one source of unmodeled timid behavior.
    apparentDecel: Optional[float] = None
    emergencyDecel: float = 9.0
    # Source for each field, used in the XML comment block.
    provenance: dict = None  # type: ignore[assignment]

    def __post_init__(self):
        if self.apparentDecel is None:
            self.apparentDecel = self.decel
        if self.provenance is None:
            self.provenance = {
                "accel": "HCM 6 typical passenger car",
                "decel": "AASHTO Green Book comfortable decel (3.4 m/s^2) "
                         "rounded up to SUMO default 4.5",
                "tau": "Krauss original 1.0s; SUMO default",
                "sigma": "SUMO default driver imperfection (0.5)",
                "minGap": "SUMO default; 2.5m queue gap",
                "maxSpeed": "50 mph corridor speed limit -> 22.22 m/s",
                "length": "passenger car typical 5.0m",
                "apparentDecel": "= decel (eliminates safety overshoot)",
                "emergencyDecel": "SUMO default upper bound 9.0",
            }


# Bounds used by the optional grid search. Wide enough to cover the
# realistic spread of arterial driver behavior; narrow enough to keep
# the search to ~125 combinations.
GRID_TAU = (0.7, 1.0, 1.3)
GRID_SIGMA = (0.3, 0.5, 0.7)
GRID_DECEL = (3.5, 4.5, 5.5)


def write_vtypes_xml(out_path: str, params: KraussParams,
                     fitted_against: Optional[dict] = None) -> None:
    """Write the additional-files-compatible vType block. Provenance
    lives in XML comments so SUMO ignores it without complaint."""
    p = params
    src = p.provenance
    header_lines = [
        '<additional>',
        '  <!-- Generated by ai.sumo_calibration.calibrate_carfollow.',
        f'       UTC timestamp: {_dt.datetime.utcnow().isoformat()}Z',
    ]
    if fitted_against:
        header_lines.append(
            f'       Fitted against: '
            f'{json.dumps(fitted_against, sort_keys=True)}')
    else:
        header_lines.append(
            '       Mode: literature defaults (no empirical fit: '
            'see report.md R3).')
    header_lines.append('       Per-field provenance:')
    for k, v in src.items():
        header_lines.append(f'         {k:<16} = {v}')
    header_lines.append('  -->')

    vtype = (
        f'  <vType id="passenger_calibrated" vClass="passenger" '
        f'carFollowModel="Krauss"\n'
        f'         accel="{p.accel}" decel="{p.decel}" '
        f'apparentDecel="{p.apparentDecel}" '
        f'emergencyDecel="{p.emergencyDecel}"\n'
        f'         tau="{p.tau}" sigma="{p.sigma}" minGap="{p.minGap}" '
        f'maxSpeed="{p.maxSpeed}" length="{p.length}"/>'
    )

    body = "\n".join(header_lines) + "\n" + vtype + "\n</additional>\n"
    Path(out_path).write_text(body, encoding="utf-8")


# ---------- optional grid search (requires SUMO on PATH) ----------

def _run_one_sim_and_measure_flow(
    sumo_cfg: str, bottleneck_edge: str,
    params: KraussParams, sim_duration: int = 600,
) -> float:
    """Run SUMO for ``sim_duration`` seconds with the given vType
    swapped in, measuring the discharge rate (veh/h) on
    ``bottleneck_edge``. Steady-state assumed after a 60s warmup.

    Imports traci lazily so the literature-defaults path stays
    runnable on machines without SUMO installed.
    """
    import traci  # noqa: F401
    # Implementation deferred: needs a one-off vTypes file + sumocfg
    # variant per (tau, sigma, decel) candidate. Sketch only -- gated
    # on saturation-flow ground truth landing first.
    raise NotImplementedError(
        "Grid-search calibration is a stub. Activate once "
        "saturation-flow surveys are in (report.md R3). The function "
        "signature is the contract: it must return measured discharge "
        "in veh/h on the named bottleneck edge."
    )


def grid_search_against_target(
    sumo_cfg: str, bottleneck_edge: str, target_flow_vph: float,
) -> tuple:
    """Brute-force best (tau, sigma, decel) against the measured target
    discharge flow. Returns ``(best_params, best_loss, all_scores)``.
    """
    best = None
    scores = []
    for tau in GRID_TAU:
        for sigma in GRID_SIGMA:
            for decel in GRID_DECEL:
                params = KraussParams(tau=tau, sigma=sigma, decel=decel)
                measured = _run_one_sim_and_measure_flow(
                    sumo_cfg, bottleneck_edge, params)
                loss = (measured - target_flow_vph) ** 2
                scores.append({
                    "tau": tau, "sigma": sigma, "decel": decel,
                    "measured_vph": measured, "loss": loss,
                })
                if best is None or loss < best[1]:
                    best = (params, loss)
    return (best[0], best[1], scores)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--out",
                   default="vTypes_calibrated.add.xml")
    p.add_argument("--saturation-flow-target", type=float, default=None,
                   help="Target veh/h/lane to fit against (triggers "
                        "grid search). Requires --bottleneck-edge and "
                        "--sumo-cfg.")
    p.add_argument("--bottleneck-edge", default=None)
    p.add_argument("--sumo-cfg", default="sim_calibrated.sumocfg")
    p.add_argument("--report-out", default=None,
                   help="Optional JSON path to dump the full search "
                        "scores when grid search runs.")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    if args.saturation_flow_target is not None:
        if not args.bottleneck_edge:
            print("ERROR: --saturation-flow-target requires "
                  "--bottleneck-edge.")
            return 2
        print(f"Grid-search calibration: target "
              f"{args.saturation_flow_target} veh/h on "
              f"{args.bottleneck_edge} (cfg={args.sumo_cfg}).")
        try:
            params, loss, scores = grid_search_against_target(
                sumo_cfg=args.sumo_cfg,
                bottleneck_edge=args.bottleneck_edge,
                target_flow_vph=args.saturation_flow_target,
            )
        except NotImplementedError as e:
            print(f"ERROR: {e}")
            return 3
        fitted = {
            "target_vph": args.saturation_flow_target,
            "bottleneck_edge": args.bottleneck_edge,
            "loss": loss,
            "tau": params.tau, "sigma": params.sigma,
            "decel": params.decel,
        }
        write_vtypes_xml(args.out, params, fitted_against=fitted)
        if args.report_out:
            Path(args.report_out).write_text(
                json.dumps({"best": fitted, "all": scores}, indent=2)
                + "\n", encoding="utf-8")
        print(f"Wrote {args.out} (fitted).")
        return 0

    # Default: literature-anchored vTypes.
    params = KraussParams()
    write_vtypes_xml(args.out, params, fitted_against=None)
    print(f"Wrote {args.out} (literature defaults; no empirical fit).")
    print("Run with --saturation-flow-target once sat-flow surveys land "
          "(see report.md R3).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
